### ISSUE TITLE
images differences are captured correctly but robot test is passing even when there is a difference with tolerance set to zero

### ISSUE THREAD

**Issue by abdalhamidElnaggar** [jz-jess/RobotEyes#103]
**Describe the bug**
robot test is passing even when there is difference between two images and tolerance is set to 0 

**To Reproduce**
1-create new test to compare two images by compare  images keyword or compare two images
2-make sure there is a difference between the two images
3-run the test and check robot result

**Expected behavior**
robot test should fail as there is a difference between the two images
**Screenshots**
attached the two images and the diff one
**Desktop (please complete the following information):**
 - OS: MacOS venture 13.3
 - Browser : chrome
 - Version :110

**Additional context**
![robot_test](https://user-images.githubusercontent.com/75017640/224508259-aee521b3-5642-4029-8fe6-a6878c35d8f1.png)
![home_ref](https://user-images.githubusercontent.com/75017640/224508260-cdfab919-d4a9-4ef0-bbe7-6d435276821f.png)
![home_actual](https://user-images.githubusercontent.com/75017640/224508263-682a6876-ab5c-43b3-8c98-fdf551d88642.png)
![home_diff](https://user-images.githubusercontent.com/75017640/224508267-22eb0e16-9604-4218-b42b-5db51cb6e1dc.png)

**Comment by abdalhamidElnaggar** [comment]
it seems like magick is returning the difference as 0 , can this be an issue with magick ?

**Comment by jz-jess** [comment]
@abdalhamidElnaggar I took a look at this. Magick returns a difference of 0.002 which is a difference of 0.2%. This gets casted to int which is converting the different into 0. I'll fix the code to retain the exact value instead of doing the int conversion.

Meanwhile a workaround for this could be to use `capture element` keyword and capture a portion of the page (headers for example). This should return a higher difference value for the mismatch and would result in a failure

**Comment by abdalhamidElnaggar** [comment]
@jz-jess thank you .. i will wait for the fix as my plan is to compare full pages not just elements.
thanks again much appreciated.
